channels:
- conda-forge
dependencies:
- fsspec == 2021.11.0
- make
- mypy
- netcdf4
- numpy == 1.22.0
- pytest
- pytest-cov
- rasterio == 1.2.4
- rioxarray == 0.8.0
- shapely
- types-setuptools
- xarray == 0.22.2
- xmlschema == 1.9.0
- zarr
